spring:
  application:
    name: liverpool-dev
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/liverpool_db}
      auto-index-creation: true

server:
  port: ${PORT:8088}

external:
  api:
    base-url: https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1
    items-path: /items
    pedidos-path: /pedidos

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tags-sorter: alpha

scheduling:
  sync:
    rate: 1800000

logging:
  level:
    com.liverpool.challenge: INFO
    org.springframework.web.client: DEBUG
